# Generated by Django 4.2.7 on 2023-12-01 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
